name: PR to master with a TAG
# Publish the app with the new Tag on master
# Execute only if it's a PR which comes from dev with a TAG

on:
  push:
    branches:
      - master  # No push to master allowed, but I need to listen this event, so I can reject it
  pull_request:
    branches:
      - master  # I allow only PR from dev -> master
    tags:
      - 'v*'  # This runs the workflow ONLY when a tag like v1, v2, v4, etc., is pushed

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source is dev
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "❌ Direct push to master is not allowed!"
            exit 1
          elif [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "❌ PRs to master must come from dev!"
            exit 1
          elif [[ "${{ github.head_ref }}" == "dev" ]]; then
            echo "✅ PRs to master authorized."
            exit 0
          fi

  build-and-push:
    runs-on: ubuntu-latest
    needs: validate-branch  # Only runs if validation passes
    if: success()  # Ensures the first job succeeds

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Extract Git Tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository }}:latest
          file: ./Dockerfile
