# Execute on every push or PR to dev
name: Push or PR to dev
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  #-----------------------------------------------------------------------
  #--- Test the service
  #-----------------------------------------------------------------------
  test-service:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven and Run Tests
        run: |
          chmod +x mvnw
          ./mvnw clean test
